src/image.rs
Hello, @trimental!
I just took a look at source code and found this little opportunity for improvement. That is it.
=> Use and_then

.github/workflows/CI.yml
Nothing too exciting. It adds a linux runner and adds a cache action for build artifacts
=> Beef up ci

Cargo.lock, Cargo.toml, README.md, src/image.rs, src/interpreter.rs, src/main.rs, src/renderer.rs, src/utils.rs
Definitely an exciting PR that adds live reloading by watching the file directory for changes and then sending new string data to the interpreter. Live reloading is one of the things I most wanted for inlyne so I'm glad to at least get a proof of concept PR out.
There a few graphical glitches I'm experiencing on macOS with partial rendering which could be the same as stated in https://github.com/trimental/inlyne/issues/21. Honestly after looking into it I'm tempted to think it might be a wgpu issue, as it seems it takes two redraws for things drawn previously to show to the screen. Maybe a swap chain issue? I'll have to look into it more.
@LovecraftianHorror If you have the time to quickly help test this on linux when you get a chance that would be a great help even if it's on the weekend …
=> Live reloading (exciting)

src/main.rs
=>  #48 Add support for relative links by prefixing them with the currently

src/main.rs
held down, open them in a new window instead
=>  #50 open local md files in current window when clicking - if SHIFT is

inlyne.toml.sample, src/main.rs, src/opts/cli.rs, src/opts/config.rs, src/opts/mod.rs, src/opts/tests.rs, src/positioner.rs, src/renderer.rs
Only tested it a little, seems to work.
=> added page_width option to limit rendering width.

Cargo.toml, README.md
=> Spelling: 'browsless' -> 'browserless'

Cargo.toml
This is a boring release to just get the `--page-width` fix out
This commit is tagged with v0.3.1 which I can push after this is merged
=> Release v0.3.1

Cargo.lock, Cargo.toml, xtask/Cargo.toml
Just filling out some more `Cargo.toml` info
=> Fill in more `Cargo.toml` values

src/interpreter.rs
Resolves #90
A footnote will will generate an `"id"` on both the hyperlink on the main text and the list item on the footnote that both serve as anchors. The generated html is as follows
```html
<p>Like this<sup class="footnote-ref"><a href="#fn-1" id="fnref-1" data-footnote-ref>1</a></sup>.</p>
<section class="footnotes" data-footnotes>
<ol>
<li id="fn-1">
<p>A <a href="https://www.markdownguide.org/extended-syntax/#footnotes">footnote</a> <a href="#fnref-1" class="footnote-backref" data-footnote-backref aria-label="Back to content">↩</a></p>
</li>
</ol>
</section>
```
Where in the above `#fn-1` is the anchor for the main text and `#fnref-1` is the anchor for the footnote
The footnote on the list item is a little awkward since the anchor is positioned in `Positioner::position()` which …
=> Anchorize footnotes

Cargo.toml, src/main.rs
- Fix for #55
- Adds `x11` and `wayland` (default) features-- so users can opt out if they so choose
=> Fix for Wayland, Make X11 and Wayland features

src/watcher/tests.rs
I still occasionally see the watcher test fail when either pushing to my fork or opening PRs here. I can't reproduce the failures locally, but it looks like they only sporadically fail on mac or windows, so that makes sense
This changes the test to allow for 3 total runs with increased delays when waiting for things each run. I figure the tests would probably pass when using longer delays in general, but I want test suite runs to be as fast as possible. This allows for successes to finish quickly while allowing for more time when things do start failing
=> Retry watcher test with increased delays

src/interpreter/mod.rs, src/interpreter/snapshots/inlyne__interpreter__tests__nested_ordered_list.snap, src/interpreter/snapshots/inlyne__interpreter__tests__ordered_list_in_unordered.snap, src/interpreter/snapshots/inlyne__interpreter__tests__unordered_list_in_ordered.snap, src/interpreter/tests.rs
The logic was already 99% correct. It just needed to `break` after finding the last list element instead of iterating all the way to the first
There's also an unnecessary space that's included with the outer list element when it has a nested list, but it's with whitespace logic that I really don't want to touch until we have a much more thorough test suite built up
=> Fix-up nested lists

src/interpreter/tests.rs
@Valentin271 this should greatly reduce the likelihood of hitting that one spurious CI failure that you hit in #220
Now the default timeout for declaring an interpreter test dead is 8 seconds and that one specific test that seems really slow only in windows CI is given a timeout of 16 seconds instead
=> Reduce the likelihood of a specific spurious CI failure

.github/workflows/CI.yml, Cargo.lock, Cargo.toml, src/clipboard.rs, src/main.rs
This _should_ fix things, so that the clipboard works on wayland (based off `alacritty`'s clipboard code)
=> Add clipboard support for wayland

Cargo.lock, Cargo.toml
=> Enable `fontconfig` feature for transitive `fontdb` dep

Cargo.toml
We have an org now! :tada: (thanks @trimental!)
=> Update repository link to use new org

src/main.rs
This makes `Inlyne` behaves like GitHub in this situation. And when the user clicks on a relative link, it'll take the user to the first place that a header with the same name appears (regardless of their cases).
To point to a different header with the same name, can use numbering,, adding the suffix (`-N`) with `N < 0`). Excepts for the first header.
```md
- [Header-0](#HEADER)
- [hEader-1](#header-1)
- [header-2](#header-2)
In hac habitasse platea dictumst. Donec ac tincidunt enim, ac egestas leo. Donec in odio sapien. Proin fermentum leo vel lectus molestie accumsan. Suspendisse potenti. Etiam in augue nisi. Etiam a ipsum eget enim ultricies vulputate id eget libero.
Sed ultricies mi eu sapien sagittis, euismod vulputate ex condimentum. Proin sit amet convallis nisi, in varius ligula. …
```
=> fix(links): ignore the case when look-up for an anchor

README.md
| Before | After |
| :---: | :---: |
| ![Packaging status](https://repology.org/badge/vertical-allrepos/inlyne.svg) | ![Packaging status](https://repology.org/badge/vertical-allrepos/inlyne.svg?exclude_unsupported=1) |
=> Exclude unsupported package repos from repology badge

src/main.rs, src/utils.rs
Fixes #259
Moves all the common logic for changing a file behind `Inlyne::update_file()`
=> fix: Update the title on file changes

README.md
This adds things I noticed in https://github.com/Inlyne-Project/inlyne/issues/263#issuecomment-2002283256 to the official installation docs
=> doc(readme): Improve installation docs

src/interpreter/mod.rs, src/main.rs
Resolves lints that are angry on the beta toolchain before it ends up coming to stable
=> chore: Resolve beta clippy lints

Cargo.lock
=> chore(deps): Let `cargo` update the lockfile

Cargo.lock, Cargo.toml, README.md, src/main.rs, src/renderer.rs, src/text.rs, typos.toml
(re-opening of #299 with the right branch name this time)
Figured that the next breaking release is far enough away that it's worth backporting some things in the meantime
Planning on cutting the actual release tomorrow after I have time to double check things
=> v0.4.2 backportapalooza

src/main.rs, src/renderer.rs
=> feat: scroll when clicking the scrollbar

src/renderer.rs
=> fix: align checkboxes to line instead of box

.github/workflows/release.yml, assets/inlyne.desktop
Commit messages explain the changes well enough
=> Tweak .desktop file

src/test_utils.rs
Simplifies some things and allows for easily creating more complex servers by passing in generic functions with different states. Not needed for much now, but will be useful for writing tests for the image cache once that's a thing
=> refactor: Simplify file server

Cargo.lock, Cargo.toml, src/image/decode.rs, src/interpreter/snapshots/inlyne__interpreter__tests__image_loading_fails_gracefully.snap
So long streamed image decoding :saluting_face:
=> refactor: Bump image version and remove streamed decoding

Cargo.lock, Cargo.toml, src/panic_hook.rs
Some breaking changes, but nothing too major
=> refactor: Update `human_panic` to v2.0.0

src/main.rs, src/renderer.rs
Fixes #330 and another bug (look commit msg)
=> fix: selection bugs

src/main.rs
=> feat: add class window propertie on wayland

.github/workflows/CI.yml, src/main.rs
=> Fix windows wayland build issue

codecov.yml
Hopefully the final annoying thing that nukes CI's signal to noise ratio
=> chore: Disable codecov patch check

Cargo.lock, src/main.rs
=> deps: `$ cargo update -p time`

src/main.rs, src/opts/config.rs
=> Make `inlyne config open` reject invalid configs

Cargo.lock, Cargo.toml, xtask/Cargo.toml
Just handling trivial updates for now
=> Trivial dependency updates

src/interpreter/mod.rs, src/interpreter/tests.rs, src/main.rs
=> refactor: Replace `VecDeque` usage with `Vec`
