Inlyne-Project/inlyne

Cargo.toml
It looks like this was added when when doing some profiling. Not including debug info makes the binary size a lot smaller for Linux users
=> Remove `debug = true` for release builds

src/main.rs
Partially resolves #3
This could be improved by calculating a more appropriate value to scroll by line, but this change at least makes things more usable when line-delta scrolling is used
=> Have line-delta scrolling shift by 30 pixels per line

Cargo.lock, Cargo.toml, src/main.rs
This change just tries to provide a friendlier message when there is a failure reading from the provided file
_Before_
```console
$ inlyne missing_file.md
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:890:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
_After_
```console
$ inlyne missing_file.md
Error: Error reading file at "missing_file.md"
Caused by:
No such file or directory (os error 2)
```
=> Improve error message when file path isnt a file

Cargo.lock, Cargo.toml, src/image.rs
`reqwest` has a pretty heavy dependency tree considering it is only used once in `inlyne`. On top of that it still pulls in `tokio` when  the rest of the application isn't `async`
Swapping to `ureq` shaves off a healthy amount of dependencies which reduces build times and reduces the final binary size by ~1 MiB for me
=> Swap `reqwest` out for `ureq`

Cargo.lock, Cargo.toml, src/color.rs, src/interpreter.rs, src/text.rs
Resolves #8
_The `comrak` feature tweaking is to get rid of the default `clap` feature which is only useful for the `comrak` binary_
This implements the initial support for syntax highlighting code blocks, but it seems there are some bugs in how some spans with just whitespace are handled (e.g. the lines starting with `async` and `return`) which I would appreciate some help troubleshooting since the `TokenPrinter` is a big ball of mutable state that is pretty hard to follow.
Here is some of the syntax highlighted code where the indentation is having some obvious issues. The indentation issues are reproducible when just having `comrak` include colored spans in codeblocks without any of the code for respecting the span's color
_Before_
_After_
---
Also worth noting that the HTML portion of …
=> Initial codeblock syntax highlighting support

src/image.rs
I know I said I was done with changes before the next release, but I was trying to figure out why some of the images had some obvious fuzziness. Setting an anisotropy clamp cleared it up, and from what I can tell this seems to have minimal impact on GPU usage (not surprising since this isn't an image heavy program)
All of these images are from using a window that is one quarter the size of my monitor with a scale of 1.5 since this exacerbates the issue. The second image is portion from the last image in bun's README
_Before_
_After_
=> Switch image min and mipmap filters to linear

src/interpreter.rs, src/utils.rs
This PR was motivated by the decoration at the top of [`insta`'s README](https://github.com/mitsuhiko/insta/blob/master/README.md)
```html
<div align="center">
<p><strong>insta: a snapshot testing library for Rust</strong></p>
</div>
```
The two aspects of this PR are
1. Pushing div alignment onto the element stack
2. Only set `current_textbox` alignment when found
_Before_
_After_
=> Allow for specifying alignment in `<div>`s

src/color.rs
The inline code color looks a bit out of place now that there code blocks have syntax highlighting
This PR changes the inline code colors based by picking an arbitrary color from the syntax highlighting. I just tried to pick a color that was both distinct from regular text color, link color, and something that would look like a clicked link color (I know the color doesn't change when they're clicked)
Feel free to bikeshed the colors!
_Before Light_
_After Light_
_Before Dark_
_After Dark_
=> Tweak inline code colors

src/main.rs, src/table.rs, src/text.rs, src/utils.rs
The main motivation behind all of this is that clicking links without moving the mouse wouldn't actually open the link. This is because link clicking was implemented in a position change event, so pressing and releasing the LMB without moving the cursor wouldn't trigger it
This was fixed by moving the link clicking logic into the LMB press event. Most of the work here was refactoring to decouple the hover element checking from link clicking to avoid duplicating a bunch of logic
The scrollbar could use similar changes since it suffers from the same problem of clicks not registering unless the cursor is moved while clicking, but this is all I have time for tonight
=> Fixup link clicking

src/main.rs, src/opts/cli.rs, src/opts/mod.rs, src/opts/tests.rs
Allows for inline to spawn a new instance of itself along with the same command line arguments in order to preview markdown files that are linked with a relative path.
=> Open markdown file links with inlyne

src/main.rs, src/renderer.rs
Resolves #25 
The comment linked below covers things pretty well. The gist is that we can lazily handle window resizing since we will get a `RedrawRequested` afterwards. This prevents a bunch of `WindowResized`s from clogging up the event queue
https://github.com/trimental/inlyne/compare/main...LovecraftianHorror:give-me-window-resizes-or-give-me-death?expand=1#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR191-R216
=> Give me window resizes or give me death

src/interpreter.rs, src/main.rs, src/positioner.rs, src/renderer.rs, src/text.rs, src/utils.rs
Adds initial inline image support by implementing a new `Row` element type (exciting 🤯 🎊). I was expecting horizontal positioning to be more of a challenge, although granted I haven't searched too deeply for bugs yet. 
Hopefully this solves https://github.com/trimental/inlyne/issues/17. Interested in @LovecraftianHorror opinion on this PR and whether it solves his issue in a nice enough way.
Here's a beautiful image to really sell the PR!
=> Add initial inline image support

src/image.rs
Tiny little change
Some of the raw image data can be pretty big (the largest image in bun's README is 55 MiB raw). This tiny change avoids copying the image data if the `DynamicImage` is already in the rgba8 format. This lowers the peak memory usage of loading bun's README by 55 MiB
=> Avoid copying image data when possible

Cargo.lock, Cargo.toml, src/main.rs
I opted for `env_logger` since I like the filtering options it provides, but I would be open to alternatives (I also like `tracing-subscriber`)
The env var for filtering is `INLYNE_LOG`. By default dependencies only show `Error`s while `inlyne` shows `Info` and up to keep the default output from being very noisy
=> Add initial logging support

src/main.rs
This changes the title to include the filepath to the file being viewed
I figured what people would want 90% of the time would be the relative path from the repo root, so that is what this PR implements. If it doesn't detect a repo root then it falls back to the full filepath
=> Add filepath to title

Cargo.lock, Cargo.toml, src/fonts.rs, src/renderer.rs
> I think I see a way that things can be sped up, but I won't have time to try hacking things together till this weekend
Well I mentioned it before so here I am!
This PR involves two changes to improve performance with fonts in both the time to select them and the amount of memory usage used when loading them
1. Cache the matches when specifying a custom font family
2. Memmap the font files to avoid loading them fully into memory
This involved a bit more spaghetti logic than I wanted, but there was a lot of trying things based on if the cache exists, falling back, and resetting the cache involved which ends up looking a little messy. The basic idea is that we store the results returned by `.select_best_match()` when a custom font family is specified in `inlyne.toml`. These get stored in …
=> Font optimizations

README.md, src/interpreter.rs, src/main.rs, src/positioner.rs, src/renderer.rs
Adds support for hidden text through the html details and summary tags. A new rendering element called `Section` was added to help with this which might prove useful in the future as it's basically the vertical version of `Row`. 
A little triangular marker is placed next to the summary text to show the hidden state.
=> Add details and summary support (hidden text)

Cargo.lock, Cargo.toml, inlyne.toml.sample, src/opts/cli.rs, src/opts/mod.rs, src/opts/tests.rs
This change _should_ change the default theme to detect the system setting when possible. This is represented by a new `auto` variant
I would certainly appreciate someone else testing that this actually works. Linux's system settings are heavily non-standardized to put it nicely and the setup I use does not indicate its theme preference in a way that gets detected
=> Default to system theme

.github/workflows/release.yml, Cargo.toml
This creates a custom profile intended for published releases
I toggled on fat lto because it significantly slims down the final binary for me from 18.3 MiB to 15.2 MiB both stripped (probably also speeds things up a chunk too, but it was already pretty fast anyways). I opted for a custom profile because it **significantly** slows down release builds for me (like going from 2m30s to 4m30s for a clean release build on my laptop), so this way it's easy to only use the profile for actual releases
=> Use a custom profile for building releases

src/opts/tests.rs
Adding the auto theme detection accidentally caused tests to fail on systems that had a dark theme set
I'm planning on cleaning things up in a follow-up PR, but these fixes things to work regardless of system theme
=> Tests no longer fail depending on system color scheme

Cargo.lock, Cargo.toml, src/opts/cli.rs, src/opts/config.rs, src/opts/mod.rs, src/opts/tests.rs
Followup on the whole system-theme detection for testing
This makes it so that tests always explicitly pass what theme is being used instead of having the system theme detected. Detecting the system theme in tests is obviously problematic because it leads to different behavior depending on the system being tested on
=> Don't detect system theme in tests

.github/workflows/release.yml, Cargo.lock, Cargo.toml, src/opts/cli.rs
This adds a flag (`--gen-completions <shell>`) that generates shell completions to stdout. It also changes CI so that all completions _should_ be generated and provided up front (assuming I didn't subtly bork the release CI job)
I can confirm that it works on zsh for me
=> Add flag for generating shell completions

Cargo.lock, Cargo.toml, src/image.rs, src/utils.rs
Resolves #45
(Well not quite, but it's a considerable improvement for now)
This PR changes the raw image data to be stored as LZ4 Frame Format blobs. LZ4 because it's got very fast compression/decompression speeds and the frame format because `lz4_flex`'s block format stores the output in a `Vec` allocated for the maximum possible output size which leads to a pretty large memory spike. Granted Linux (and Mac?) typically doesn't allocated zero'd pages until they're actually used for something else, but I figured the lower memory spike was worth the extra code complexity to handle streaming
https://user-images.githubusercontent.com/30302768/229645749-dc4daaea-e092-4fba-84b2-ac4b9e84912d.mp4
Above you can see that with this PR scrolling over all of `bun`'s README is typically a steady ~20 …
=> Store raw image data as LZ4 compressed blobs

Cargo.lock, Cargo.toml, src/fonts.rs, src/image.rs, src/interpreter.rs, src/main.rs, src/opts/cli.rs, src/opts/config.rs, src/positioner.rs, src/renderer.rs, src/utils.rs
Use Tokio to make everything async instead of using threads. This mainly impacts image loading which used to use thread spacing before. I feel as though this is a bit cleaner at the cost of feeling a bit 'magic-like'. I'm interested to hear your thoughts about this @CosmicHorrorDev. 
I haven't done any benchmarking against the old implementation yet. This should help with streaming images directly into a compressed format.
=> Make everything async

src/text.rs
This just cleans up the `font_id` function.
=> Refactor: Clean up `font_id` selection.

.github/workflows/release.yml
For some reason this is failing in CI with a bad cpu type
In the future we generate these static assets before-hand or have them generated from a build script instead of generating them at run-time in the release pipeline
Would be good to repush the release tag after this is merged
=> Temporarily skip generating completions for aarch64-apple-darwin release

src/keybindings/defaults.rs, src/keybindings/mod.rs
One less thing that I need in my `inlyne.toml` file now :grin:
This adds:
- y ->  Copy
- k -> Scroll up
- j -> Scroll down
- gg -> Top of doc
- G -> Bottom of doc
- q, ZZ, ZQ, Escape -> quit
=> Add vim-like bindings (and escape) to the defaults

src/keybindings/defaults.rs, src/keybindings/mod.rs, src/keybindings/tests.rs, src/main.rs, src/opts/cli.rs, src/opts/config.rs, src/opts/mod.rs, src/opts/tests.rs
This PR cleans up some aspects of the configuration management. It also implements #84. This also fixes the long form `page width` flag, which was previously broken.
=> Some clean ups, fixes, config flag

src/main.rs
Fixes #95 
Markdown (or at least GitHub's markdown w/ extensions) supports bare relative links like
```markdown
[link](some_file.md)
```
But this would fail when trying to strip the current directory prefix because there isn't one
Manually tested that this still works with anchors, paths prefixed with `./`, etc. This whole section could use a refactor and some automated testing
=> Support bare relative links

Cargo.lock, Cargo.toml, src/interpreter.rs, src/utils.rs
Resolves #93
This adds in basic YAML front-matter support (basic in the sense that I couldn't find any documentation on what GitHub's front-matter supports, so I just worked off the provided example)
The example provided in #93 created a nested table, but `inlyne` doesn't handle rendering that correctly yet (#110), so instead `{Skipped nested table}` placeholder text is inserted and a warning log is emitted
```md
---
title: Title
date: 2018-05-01
tags:
- another tag
---
body
```
**Rendered by `inlyne`**
=> Basic YAML front-matter support

src/keybindings/defaults.rs, src/keybindings/mod.rs, src/main.rs
I opted for scrolling 90% of the current page height since scrolling a full page seemed like it would be a bit jarring. Scrolling slightly less than a full page seems to be a common way of handling things from looking at how other programs manage it
=> Add ability to scroll with PageUp/PageDown

src/opts/tests.rs
The `--'page width'` flag slipping through. Add a test with all CLI options that can help to catch future issues before getting merged
=> Add a test for all CLI options

src/keybindings/action.rs, src/keybindings/defaults.rs, src/keybindings/mod.rs, src/keybindings/serialization.rs, src/keybindings/tests.rs, src/main.rs
This avoids a lot of the `unreachable!()`s in `main.rs` while pushing most of the complexity off on `serde`
=> Make invalid states unreachable

README.md
Swaps out the package manager specific installation instructions for a repology badge that links to a page with various installation information. The listing is decently comprehensive and will stay up to date
The current listing as viewed through `inlyne`
=> Add repology badge for package manager installation

Cargo.lock
The gist: `zbus` related version changes broke D-Bus usage which meant Linux system theme detection wouldn't always work
#105 bumped the `zbus` version down to v3.10.0 which fails connecting to the D-Bus session when used with newer versions of `zvariant` (https://github.com/dbus2/zbus/issues/328). This just tweaks the lock-file to get a newer version of `zbus` where the issue is fixed at the expense of pulling in multiple `nix` versions
Since this is just a linux specific lockfile change I'm planning on merging after CI passes
=> Fix outdated zbus bug

Cargo.lock, Cargo.toml, src/utils.rs
This adds support for parsing emoji shortcodes like `:tada:`
Should probably wait until after #105 is merged, so that rendering emojis is in better shape
=> Support parsing shortcodes

Cargo.lock, Cargo.toml, src/renderer.rs
Two major PRs we're waiting on are https://github.com/grovesNL/glyphon/pull/34 and https://github.com/pop-os/cosmic-text/pull/132. That implement text texture atlas growth and monospace fallback respectively.
Looking at the activity of both crates it might be a while until these can make it into the codebase. Will probably be a good idea to switch back once these two PR's are merged.
=> Fork glyphon and cosmic-text

README.md
I had to look up the `dirs` documentation to work out where the config directory was on macOS, and I had to look through the inlyne source code to determine that the file was nested under a directory called `inlyne`.
=> Make correct location of `inlyne.toml` file clearer

Cargo.lock, src/color.rs, src/interpreter.rs
Looks like we both ended up making pretty similar changes :laughing: 
This switches the default theme to `InspiredGitHub`, adds support for `font-style` since the code highlighting also makes use of that, and overrides the background color to match the background color used by GitHub
=> Default light theme to modified `InspiredGitHub`

Cargo.lock, Cargo.toml, src/interpreter.rs, src/utils.rs
This properly handles modifying Inspired GitHub's background color without the hack in the interpreter
The themes in a `ThemeSet` are just stored in `BTreeMap`, so we could always choose to load in our own default `inlyne-light` and `inlyne-dark` themes if desired
=> Properly modify InspiredGitHub's background color

inlyne.default.toml, src/color.rs, src/interpreter.rs, src/main.rs, src/opts/config.rs, src/opts/mod.rs, src/opts/tests.rs, src/utils.rs, tests/assets/sample.tmTheme
The recent syntect plugin work had me thinking about how much work it would be to allow for custom themes outside of the ones bundled with syntect. Turns out the answer is not _too_ much, but there's definitely some changes I want to submit upstream for `comrak` and `syntect`
This allows for specifying custom themes by passing a `.tmTheme` file like so
```toml
[dark-theme]
code-highlighter.path = "/path/to/theme.tmTheme"
```
while still supporting the old method for specifying any of the bundled themes. There was a lot of reworking to pass around the actual syntect `Theme` instead of the enum specifying which bundled theme to use, but other than that the changes were pretty simple
When using a slightly modified (this theme could use a lot more work though): …
=> Add support for custom syntax themes

src/interpreter.rs, src/main.rs
_Probably best to review the two commits separately. This probably should have been two PRs, but here we are :sweat_smile:_
The issue was that the code for pushing the list prefix would only check the last element pushed in the `element_stack` when processing `CharacterTokens(_)`, but the footnote reference generates the following HTML
```html
<section class="footnotes" data-footnotes>
<ol>
<li id="fn-1">
<p>A <a href="https://www.markdownguide.org/extended-syntax/#footnotes">footnote</a> <a href="#fnref-1" class="footnote-backref" data-footnote-backref aria-label="Back to content">↩</a></p>
</li>
</ol>
</section>
```
which means that a `ListItem` is pushed on followed by a `Paragraph(_)` before hitting any character tokens
This PR changes things to set a `pending_list_prefix` when …
=> Fix footnote numbered list

CONTRIBUTING.md
I originally just wanted to add a release checklist, but the most fitting place to me would be in a `CONTRIBUTING.md` file, so I figured I would go ahead and throw a basic one together
=> Add a basic `CONTRIBUTING.md` doc

src/interpreter/mod.rs, src/text.rs
Adds table item horizontal alignment as shown below:
Looks like wrapping is still occurring in some weird places, might just be some f32 nonsense with the bounds changing slightly between rendering and layingout
=> Table Alignment

src/opts/cli.rs
Makes the argument required by `clap` so that the program prints a useful error message and exits when the `file` argument is missing.
Before:
```shell
$ inlyne
thread 'main' panicked at 'required', src/opts/cli.rs:101:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After:
```shell
$ inlyne
error: the following required arguments were not provided:
<FILE>
Usage: inlyne <FILE>
For more information, try '--help'.
```
=> Improve error message when no file path is provided

src/opts/cli.rs, src/opts/tests.rs
Followup to #143
I think the arg parsing regression was from changing the required args for adding the shell completions flag, and then subsequently dropping the shell completions flag
This also fixes the CLI arg parsing tests to catch `clap` errors instead of exposing the error message to stdout/stderr
=> CLI testing tweaks

CONTRIBUTING.md, Cargo.lock, Cargo.toml
Moving shell completion generation to an `xtask` left this dependency unused
=> Removed unused `clap_complete` dep

Cargo.lock, Cargo.toml, src/main.rs, src/watcher/mod.rs, src/watcher/tests.rs
Before file watching would keep watching a file even after it was renamed. File watching would also fail permanently if you did something like removing the original file and replacing with a new file after a short delay
These changes handle all of the above cases by `.unwratch()`ing the file after name changes (the path associated with the watcher is still the original path name even after a rename) and looping continuously to re-register the watcher after the original file is renamed/removed
I also added a reminder to fix watching the file after changing the file by clicking a markdown link from within the current file, but haven't handled that quite yet
=> More robust file watching

Cargo.toml
Selectively bumps up some dependency's opt level for the dev profile to make dev builds more responsive. Just looking at when the CPU would settle out while viewing bun's README this PR made it go from taking ~50s to ~5s
This will make clean dev builds take slightly longer, but it definitely seems worth it for having more responsive dev builds
=> Improve dev build perf

src/interpreter/snapshots/inlyne__interpreter__tests__bare_link_gets_autolinked.snap, src/interpreter/tests.rs, src/utils.rs
Toggles on the autolink extension and makes sure that things work fine in the places we would normally expect to see it
This extension matches GitHub's behavior, so people probably expect it to work OOTB
=> Toggle on autolink extension

Cargo.lock, Cargo.toml, src/color.rs, src/interpreter/snapshots/inlyne__interpreter__tests__handles_comma_in_info_str.snap, src/interpreter/snapshots/inlyne__interpreter__tests__toml_gets_highlighted.snap, src/interpreter/tests.rs, src/utils.rs
This fixes a couple of issues that both conveniently manifest in `reqwest`'s README
1. The default syntax definitions are missing a lot of common languages (including TOML)
2. Fenced code blocks may have an info string like ```` ```rust,ignore```` since some projects use the README for doc stuff. `comrak` doesn't recognized this as a Rust block although GitHub does
Yes the Rust highlighting is this basic for this example. It turns out that syntect is stuck using several year old syntax definitions for a lot of languages since Sublime Text has made changes to syntax definitions that would require significant changes to syntect
Part of this is also from the default dark theme. `two-face` is now getting pulled in which includes a lot more themes though, so I'll add those in a future PR
=> Improve syntax highlighting

src/color.rs, src/opts/tests/error_msg.rs, src/opts/tests/mod.rs, src/opts/tests/parse.rs, src/opts/tests/snapshots/inlyne__opts__tests__error_msg__invalid_theme_ty.snap, src/opts/tests/snapshots/inlyne__opts__tests__error_msg__unknown_theme.snap
Unfortunately switching the theme to `#[serde(untagged)]` makes the error message much worse. This fixes things back up to be nice and friendly again :)
=> Make config code highlighter error more friendly

Cargo.lock, Cargo.toml, src/debug_impls.rs, src/image/mod.rs, src/text.rs
I'm dogfooding a new crate I released primarily for the purpose of making debug impls easier to implement for things like snapshot tests. The only custom one I wasn't able to get rid of was from `Text` due to the custom formatting that merges all of the styles
=> More succinct debug impls

src/color.rs, src/image/decode.rs, src/utils.rs, src/watcher/tests.rs
Just some small tweaks that didn't feel deserving of separate PRs
=> Small cleanups

.github/workflows/release.yml
Looks like the tarball was accidentally being created before the binary was copied into it
=> Fix release tarball creation

src/image/mod.rs
Like the title says. This no longer ignores the `image_data` field when it's mutex is locked
=> Don't ignore locked mutex in debug impl

Cargo.lock, Cargo.toml, src/image/mod.rs, src/text.rs, xtask/Cargo.toml
Still need to get through `wgpu`, `winit`, and the forked `taffy` and `glyphon` versions
=> Update deps again

Cargo.lock, Cargo.toml
This solves an issue with the NixOS build where fonts are required at
runtime for inlyne to start. With the `fontconfig` feature flag inlyne
will use font-config to determine a font.
Partially resolves #164
=> fix: add missing `fontdb` feature flag

Cargo.toml
Should help `inlyne` appear higher in searches on [crates.io](https://crates.io) and [lib.rs](https://lib.rs)
=> Add relevant keywords to `Cargo.toml`

Cargo.lock, Cargo.toml, src/main.rs
This helps ensure that a baseline of helpful information gets included in future issues. Notably it will help with keeping track of the `inlyne` version that issues are reported for
=> Use `human-panic` for a custom panic hook

.github/workflows/release.yml
Release CI is a fickle beast...
Windows is the only release platform that defaults to a shell other than bash. The step for setting the version was changed with bash in mind which caused it to fail on windows. This caused the artifact name to have an empty space instead of the version
The fix is to simply use bash on all platforms
=> Correctly set the version for windows releases

Cargo.lock, Cargo.toml
I noticed that the request for the repology badge on `inlyne`'s README fails on Windows due to some weird TLS thingy. I vaguely remember trimental mentioning this in the past too when he was using Windows. Since it seems to be an issue with a vanilla Windows 10 install it's probably good to fix this
Luckily switching to `rustls` seems to be enough to fix the issue. Beyond that we become a little more portable to build in exchange for a slightly larger binary size which seems fine to me
=> Switch tls lib from `openssl` to `rustls`

Cargo.lock, Cargo.toml
Fixes #177
Updating dependencies in the v0.3.2 update introduced a panic that can occur with relative ease in `wgpu-core`. The simplest fix is just to pin `wgpu-core` to the version before the panic was introduced. This is only needed for `inlyne` v0.3.x since v0.4 can actually update to newer `wgpu` versions
=> Downgrade `wgpu-core` to fix panic

src/interpreter/snapshots/inlyne__interpreter__tests__code_in_ordered_list.snap, src/interpreter/snapshots/inlyne__interpreter__tests__para_in_ordered_list.snap, src/interpreter/tests.rs
Just adds tests to cover the case described in #174. This will be accompanied by a backport to fix this behavior on the v0.3 release series in the next few days
Notably also worth mentioning that this behavior isn't entirely correct since the element nested within the list item should be indented further to indicate that it is part of the list item. I opened #175 to talk about how the interpreter can be refactored to better handle this kind of stuff in the future
=> Add tests for elements nested in a list item

src/interpreter/html.rs, src/interpreter/mod.rs, src/interpreter/snapshots/inlyne__interpreter__tests__code_in_ordered_list.snap, src/interpreter/snapshots/inlyne__interpreter__tests__para_in_ordered_list.snap, src/interpreter/tests.rs, src/main.rs
This backports the fix so that elements nested within a list don't break the numbering / bullet points for all the list items that follow the nested element
=> Backport list fix

src/image/tests.rs, src/interpreter/tests.rs, src/keybindings/tests.rs, src/main.rs, src/opts/tests/error_msg.rs, src/opts/tests/parse.rs, src/test_utils.rs, src/utils.rs, src/watcher/tests.rs
Not much more than the title says. A little bit of boilerplate, but it sets things up so that logs get captured and emitted when tests fail which is nice for debugging
=> Setup logging for tests

CONTRIBUTING.md, README.md, example.png
In #187 I collected the various assets that were scattered around the repo, but in doing so I broke historic versions of the example.png in our README (like the currently published version on crates.io) since they were still pointing to the now non-existent image on `main`
This fixes that by adding a symlink to the old location that can be removed after v0.4 is published and can use a more stable image link. I've added a step to the release checklist to give us another reminder in the future
=> Fix README demo image

.github/workflows/CI.yml
`Swatinem/rust-cache` is better than our existing solutions in a few ways, but one of the problems it solves is that our existing cache keys do not take the compiler version into account, so a Rust update can leave us restoring a stale cache :(. That appears to be the cause behind some jobs rebuilding everything despite a full cache hit
=> Switch CI cache to `Swatinem/rust-cache`

.github/workflows/CI.yml, src/interpreter/mod.rs, src/keybindings/mod.rs, src/opts/config.rs, src/opts/tests/error_msg.rs, src/opts/tests/snapshots/inlyne__opts__tests__error_msg__basic_equality.snap, src/opts/tests/snapshots/inlyne__opts__tests__error_msg__fix_this_sucky_error_message.snap, src/opts/tests/snapshots/inlyne__opts__tests__error_msg__special_prefix.snap
I'd say the snapshots speak for themselves in terms of the improvement
=> Pretty up `KeyCombos` representation in user-facing errors

Cargo.toml, src/color.rs, src/file_watcher/mod.rs, src/file_watcher/tests.rs, src/image/decode.rs, src/main.rs, src/utils.rs
More refactorings and cleanups. Some somewhat more expensive things should be more responsive and the test suite now finishes in 0.26 seconds for me :rocket::rocket:
=> Late night refactors

src/file_watcher/tests.rs
With a slightly lower delay and a higher number of retries we still test for roughly the same amount of time worst case (less than 5 seconds) while being back to a faster happy path
This one should be more stable in CI
=> Speed up file watcher test happy paths

Cargo.lock, Cargo.toml, src/file_watcher/mod.rs, src/file_watcher/tests.rs, src/interpreter/mod.rs, src/main.rs, src/test_utils.rs
This fixes #198
As discussed in the issue, I refactored the file watcher to use [notify_debouncer_full](https://docs.rs/notify-debouncer-full/latest/notify_debouncer_full/index.html).
I did so with as few modifications as possible to avoid breaking anything. The most interesting part is the `DebounceEventHandler` impl in which I basically filtered unwanted and duplicate events.
The debouncer timeout of 10ms seems good for up to 100 ~ 150Kb files on my machine.
All unit tests passed locally. I've also tested with the files I was having issues with.
I also added logs I found interesting for debugging and changed the log format to show milliseconds since the file_watcher is always faster than a second.
=> fix: filter file watcher duplicate events

src/keybindings/mod.rs, src/keybindings/tests.rs
The keybindings logic could use a little TLC
=> Keybindings refactor

Cargo.lock, Cargo.toml, src/file_watcher/mod.rs, src/image/decode.rs, src/image/mod.rs, src/interpreter/mod.rs, src/keybindings/mod.rs, src/main.rs, src/test_utils.rs, src/utils.rs
Fixes #206
I've migrated `log` to `tracing`.
This is just a simple replacement for now, the logging functions and looks the same. `INLYNE_LOG` still controls the logging and the syntax is the same.
=> refactor: migrate from `log` to `tracing`

Cargo.lock, Cargo.toml, src/table.rs, src/text.rs
Updates taffy to the latest crates.io version.
There is no breaking change summary so I had to look in taffy's internal code to figure out which feature went were.
=> chore: update taffy

src/main.rs
Somehow, before opening #209, I forgot to put the default log level back to what is was, that is INFO.
=> fix: fix default log level back to info

src/main.rs
Fixes #202
Reset the scroll to top when navigating markdown files.
I think it's worth adding a test for this but I don't know where that would be.
=> fix: reset scroll on markdown navigation

CONTRIBUTING.md, src/color.rs, src/interpreter/mod.rs
Just fixed some small typos.
Do you think it is useful to include [`typos-cli`](https://github.com/crate-ci/typos) in the CI? (That's what I used to find those)
=> fix: typos

Cargo.lock, Cargo.toml, src/renderer.rs, src/text.rs
This updates glyphon the latest version.
There is still one change I need help with (marked below).
EDIT: I'll test the changes locally once I can get it to compile.
=> chore: update glyphon to 0.3

src/interpreter/mod.rs, src/interpreter/snapshots/inlyne__interpreter__tests__aligned_table.snap, src/interpreter/tests.rs
While working on https://github.com/trimental/inlyne/issues/141 I found a bug in the table alignment that I would like to fix first.
Each cell, if no explicit alignment specified, retain the alignment of the previous cell. This also occurred across table.
---
Assume the following table:
```
| left default | left forced | centered | right | left default |
| ------------ | :---------- | :------: | ----: | ------------ |
| text         | text        |   text   |  text | text         |
```
On main:
With this fix:
=> fix(table): table alignment wasn't reset properly

.github/workflows/CI.yml
Closes #203 
- test
- cargo test
- lint
- typos
- fmt
- clippy
- build-macos-arm (now builds on `stable` and `beta`)
- only build
Note that macos-arm runner exist since october 2023 but are paid and in beta for now: https://github.com/orgs/community/discussions/69211.
Once and if they get released publicly, macos-arm can be merged with build.
See https://github.com/Valentin271/inlyne/actions/runs/7600723247 for the latest successful run from my tests.
=> chore: refactor CI runs

src/text.rs
Fixes https://github.com/trimental/inlyne/issues/197
This change avoids the panic, _visually_ the behavior is the same.
However I'm not sure this is correct, because it means sometimes it won't be subtracted (and we get a wrong index?).
---
I don't get why we would need to subtract one to the index of the glyph under the cursor only if the cursor is associated with the previous frame. Also removing this `if Affinity::Before` altogether doesn't seem to change anything ...
Have I misunderstood something in my reasoning?
=> fix(text): fix substract with overflow panic

README.md
=> docs: document fontconfig dependency

inlyne.default.toml, src/color.rs, src/interpreter/snapshots/inlyne__interpreter__tests__code_block_bg_color.snap, src/interpreter/snapshots/inlyne__interpreter__tests__code_in_ordered_list.snap, src/interpreter/snapshots/inlyne__interpreter__tests__handles_comma_in_info_str.snap, src/opts/tests/snapshots/inlyne__opts__tests__error_msg__unknown_theme.snap
This switches the exposed embedded themes to a subset of all the themes provided by `two-face`. Namely I left out themes that didn't seem unique enough:
- `InspiredGithub` (compared to `Github`)
- `MonokaiExtendedBright`, and `MonokaiExtendedOrigin` (compared to `MonokaiExtended`)
Along with several others that don't make sense in `inlyne`'s context:
- `Ansi`
- `Base16`
- `Base16_256`
=> Expose additional `two-face` themes

src/color.rs, src/interpreter/html.rs, src/interpreter/mod.rs, src/interpreter/snapshots/inlyne__interpreter__tests__aligned_table.snap, src/interpreter/snapshots/inlyne__interpreter__tests__bare_link_gets_autolinked.snap, src/interpreter/snapshots/inlyne__interpreter__tests__checklist_has_no_text_prefix.snap, src/interpreter/snapshots/inlyne__interpreter__tests__code_block_bg_color.snap, src/interpreter/snapshots/inlyne__interpreter__tests__code_in_ordered_list.snap, src/interpreter/snapshots/inlyne__interpreter__tests__footnotes_list_prefix.snap, src/interpreter/snapshots/inlyne__interpreter__tests__handles_comma_in_info_str.snap, src/interpreter/snapshots/inlyne__interpreter__tests__nested_ordered_list.snap, src/interpreter/snapshots/inlyne__interpreter__tests__ordered_list_in_unordered.snap, src/interpreter/snapshots/inlyne__interpreter__tests__para_in_ordered_list.snap, src/interpreter/snapshots/inlyne__interpreter__tests__toml_gets_highlighted.snap, src/interpreter/snapshots/inlyne__interpreter__tests__underline_in_codeblock.snap, src/interpreter/snapshots/inlyne__interpreter__tests__unordered_list_in_ordered.snap, src/interpreter/snapshots/inlyne__interpreter__tests__yaml_frontmatter.snap, src/interpreter/tests.rs
When I was looking through `$ bat --list-themes` I noticed that the `Dracula` theme (which we now support) uses underlines in some parts of the syntax highlighting
---
Aside: we should support coloring underlines to match the text color
=> Support underlines in codeblock syntax highlighting

src/keybindings/keybindings.rs, src/keybindings/mod.rs, src/keybindings/tests.rs, src/opts/config.rs, src/opts/mod.rs, src/opts/tests/error_msg.rs, src/opts/tests/parse.rs
Fixes https://github.com/trimental/inlyne/issues/188
I suspect this PR will be easier to review by reviewing commits individually (that's why I left them) to understand the reasoning behind the changes. I also left some PR comments to explain some changes.
I refactored the code a bit to be easier to work with, hope that's okay with you.
=> feat: extra keybindings override base

src/renderer.rs, src/text.rs, src/utils.rs
In #221 it was noticed that underlines for colored text still use the default text color. This PR threads the color through to match the text color for underlines and strikethroughs
=> Add support for colored underlines and strikethroughs

src/renderer.rs, src/text.rs
Resolves #141 
@Valentin271 I got a better idea of the underline code after working on #225. The fix _feels_ hacky, but I'm not really familiar with the renderer and there's a lot of messy code in there to begin with :shrug:
From what I can gather `left` gets set to the x coord of the text area including the `Align`
(Includes the use of `--page-width` to check that too)
https://github.com/trimental/inlyne/assets/30302768/107b09f1-e6f4-490e-9484-b259fb3fde88
=> Make underlines and strikethroughs respect align

src/interpreter/mod.rs, src/interpreter/snapshots/inlyne__interpreter__tests__unique_anchors.snap, src/interpreter/tests.rs
Fixes #204 
`comrak`'s anchorizer is a much better fit for a markdown anchorizer than our home-rolled version
Note: (from [the docs](https://docs.rs/comrak/latest/comrak/html/struct.Anchorizer.html))
> ...
>
> To guarantee uniqueness, an anchorizer keeps track of the anchors it has returned. So, for example, to parse several MarkDown files, use a new anchorizer per file.
Resetting the anchorizer is handled by `State` (which contains the anchorizer) getting reset before each markdown file gets processed
=> Switch to `comrak`'s anchorizer

src/keybindings/defaults.rs
Resolves #186 
As mentioned in the issue these hotkeys are more in-line with what other programs default to for zoom-in and zoom-out hotkeys
=> Switch to more typical zoom-in zoom-out hotkeys

src/image/mod.rs, src/image/tests.rs, src/interpreter/html.rs, src/interpreter/mod.rs, src/interpreter/snapshots/inlyne__interpreter__tests__centered_image_with_size_align_and_link.snap, src/interpreter/tests.rs, src/keybindings/tests.rs, src/opts/tests/error_msg.rs
It's common to see images that specify pixel width/height including a `px` suffix, but `inlyne` would fail to parse the value and silently ignore it instead. This adds support for an optional `px` suffix on the pixel length
=> Allow for `px` suffix on pixel length

src/interpreter/html/attr.rs, src/interpreter/html/element.rs, src/interpreter/html/mod.rs, src/interpreter/html/style.rs, src/interpreter/html/tag_name.rs, src/interpreter/mod.rs
The `attr` and `style` stuff has enough code to deserve their own modules
=> Reorganize `interpreter`'s HTML code

src/interpreter/mod.rs, src/interpreter/snapshots/inlyne__interpreter__tests__header_inherit_align.snap, src/interpreter/tests.rs
The start of `sqlx`'s README is all sorts of messed up when rendering with `inlyne`. This partially fixes the `Install | Usage | Docs` alignment, but there's plenty of other issues that still need fixing
Namely there is extra whitespace that shouldn't be included in the `Install |     Usage |     Docs`, the clickable link regions for that whole portion are messed up, and the badges are displayed vertically when they should display inline (likely because they're center aligned when it looks like inline images currently only work when left aligned which is wrong)
=> Inherit align for headers

src/interpreter/tests.rs, src/utils.rs
Footnotes only partially work currently (anchors are attached to textboxes and footnotes make it much more common to have _multiple_ anchors within a textbox). This temporarily disables footnotes, so that v0.4 can be released without a feature that's known to be partially broken
=> Temporarily disable partial footnotes support

ci/ubuntu-install-packages
The `wayland` feature being default means that we need to install the proper dev libraries in CI for creating the pre-built releases. This _should_ (:crossed_fingers:) fix the release CI
=> Install `libwayland-dev` on ubuntu CI

.github/workflows/release.yml
There's been a lot of _fun_ issues with CI these past couple of releases. Hopefully things are smoother sailing from now on
=> Add `write-all` permission for release workflow

Cargo.toml
The exclude for the manual test data got broken when things got shifted around
=> Fix exclude for `manual_test_data`

.github/workflows/CI.yml
Before PRs would consistently trigger two identical sets of checks because they would hit the `push` _and_ `pull_request` trigger. Now it only runs on `push`es to `main` (e.g. branches merging)
=> Tweak CI run trigger to run on fewer pushes

inlyne.default.toml, src/history.rs, src/keybindings/action.rs, src/keybindings/defaults.rs, src/keybindings/serialization.rs, src/main.rs
This is a follow-up to #258 with some basic changes to finish fleshing out the feature
=> Flesh out history

src/keybindings/keybindings.rs, src/keybindings/tests.rs
This acts as a guard to catch when someone adds an `Action` but forgets a mapping from `FlatAction` meaning that we can't deserialize it. The idea is that virtually every action is bound by default, so you're reminded to add the mapping when this test fails
=> Ensure that we can always deserialize the default keybindings

src/renderer.rs
Fixes #261
```html
<table>
<tr>
<td>one</td>
<td>two</td>
</tr>
<tr>
<td>three</td>
<td>four/td>
</tr>
</table>
```
renders as
=> Fix crash when rendering headerless table

Cargo.lock, Cargo.toml, src/main.rs, src/opts/cli.rs, src/opts/mod.rs, src/opts/tests/parse.rs, xtask/src/gen.rs
For #282.
At this point, none of the (CLI)test work (nor compile).
But now it should be pretty easy to add new functionality to the CLI.
=> CLI rewrite

Cargo.lock, Cargo.toml, src/main.rs, src/panic_hook.rs
Adding a custom panic hook seemed to really help in terms of both getting people to open issues for panics along with adding a baseline of actionable info with the crash too
That being said, the default instructions to submit bug reports and the format of the report itself could be better tailored to suit our specific needs. This PR attempts to do that by providing simple instructions on searching for similar issues and submitting new issues for our repo instead of the old vague message. It also switches the report style to be a markdown fragment that can be copied to start a github issue since we don't have any kind of automated ingest and processing where a more structured format would make sense
=> refactor: Fully customize our panic hook

src/main.rs, src/opts/cli.rs, src/opts/config.rs, src/opts/mod.rs
In #131 the two things (to automatically create a config file and the ability to open them) were mentioned.
This pr adds the CLI option `inlyne config open` and it places the [inlyne.default.toml](https://github.com/Inlyne-Project/inlyne/blob/main/inlyne.default.toml) as `inlyne.toml` in the config directory when no config exists.
=> Add the automatic creation of config files and the ability to open them with the CLI.

src/text.rs
=> fix: Remove 0 character long selections

Cargo.lock, Cargo.toml, src/image/decode.rs, src/image/mod.rs, src/main.rs, src/metrics/counter.rs, src/metrics/gauge.rs, src/metrics/hist.rs, src/metrics/log_recorder.rs, src/metrics/mod.rs, src/opts/config.rs, src/opts/mod.rs, src/opts/tests/parse.rs, src/renderer.rs
This adds something that I've been wanting implemented for a while. Metrics recording and emission :tada:
There's a new section in the config file that sets the metrics recorder
```toml
[debug]
metrics = "log"
metrics = "tcp"
```
It's unset by default which uses the noop recorder (aka as cheap as it can get)
(this one took a bit of work since it implements a recorder from "scratch")
When it's set to `"log"` the metrics start getting recorded as tracing events with some metadata attached on the span. This makes it possible to filter things pretty dynamically, and is accessible as a user doesn't need to download anything else to see the values
When it's set to `"tcp"` the metrics get emitted following the default [`metrics-exporter-tcp`](https://docs.rs/metrics-exporter-tcp/0.9.0/metrics_exp …
=> feat: Setup initial metrics infrastructure

inlyne.default.toml, src/main.rs, src/opts/cli.rs, src/opts/config.rs, src/opts/mod.rs, src/opts/tests/parse.rs
This would add the possibility to set the window position with `-p` or `--position` and the window size with `-g` or `--size` as requested in #173.
And it would add the ability to do these via the config file:
```toml
[position]
x = 500
y = 200
[size]
width = 600
height = 500
```
=> feat: Add window position and size configuration options.

assets/inlyne.desktop
Adds a `.desktop` entry originally inspired by this comment https://github.com/Inlyne-Project/inlyne/issues/262#issuecomment-2025324280
Some simple testing on Pop OS seems to indicate that this works (`xdg-open` and different launchers appear to pick it up after adding the entry to ~/.local/share/applications/` and running `update-desktop-database ~/.local/share/applications`)
=> chore: Add a `.desktop` file

Cargo.lock, Cargo.toml, src/image/mod.rs, src/utils.rs
This switches our http client library that we use to fetch images from `reqwest` to `ureq`. There are some API differences between the two libraries, so things can't be handled quite the same way (primarily `ureq` doesn't have something akin to a `Client`), and there are differences in how http responses are handled, but that shouldn't have any practical impact on us unless servers are returning valid images with http error codes
This drops all the `tokio` related stuff from our (non-dev) dependency tree (20 less dependencies, and release lto builds are over a MiB smaller)
=> refactor: Switch from `reqwest` to `ureq`

Cargo.lock
Seems we're hitting this
- https://github.com/Smithay/client-toolkit/pull/406
=> chore(deps): Update `smithay-client-toolkit` from v0.16.0 -> v0.16.1

Cargo.lock, Cargo.toml, src/interpreter/mod.rs, xtask/Cargo.toml
This covers all of the simple updates with only a single line of code changed. It looks like `winit`, `glyphon`, and `wgpu` will all have to be updated in tandem, and I'm holding off on updating `image` until we can streaming image decoding of at least jpeg and png images sorted out
=> Simple dependency updates

src/interpreter/html/mod.rs, src/interpreter/mod.rs
This closes #201.
I've chosen the header sizes of the HTML spec, as that seemed reasonable.
This doesn't change the appearance of the application
Relative / Static
=> feat: use relative font size for headers

src/main.rs, src/renderer.rs, src/selection.rs, src/text.rs, src/utils.rs
=> Add double and triple click selection

Cargo.toml, src/renderer.rs
This adds bounding boxes to elements when the `debug` flag is used, as mentioned in https://github.com/Inlyne-Project/inlyne/issues/294#issuecomment-2050745847
=> feat: add debug boxes

Cargo.toml, src/opts/config.rs, src/opts/mod.rs, src/renderer.rs
Moves the render element bound toggle to a config value under the debug section aka
```toml
[debug]
render-element-bounds = false
```
=> refactor: Move element bound render toggle to config

src/renderer.rs
=> feat(renderer): skip drawing scrollbar when content fits on page

Cargo.lock, Cargo.toml, src/interpreter/tests.rs, src/main.rs, src/test_utils.rs
We really didn't need a lot of what `wiremock` provided since we really only want a small file server, so this PR switches to precisely that
=> refactor(tests): Drop wiremock

src/history.rs, src/opts/mod.rs, src/opts/tests/parse.rs
Fixes so that we no longer panic when passing `inlyne` a file path that doesn't exist again
=> fix: Dont panic on missing file path

.github/workflows/release.yml
Please end my GH suffering. This is my best guess at this point as to why the release pipeline is failing despite no workflow/organization/repo changes. Specifically this warning
```
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, svenstaro/upload-release-action@v1-release. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
_:sparkles:Lovely:sparkles:..._
=> deps: Update svenstaro/upload-release-action to 2.9.0

Cargo.toml, src/panic_hook.rs
I don't really like this aggressive of an MSRV bump, but oh well :/
=> chore: Switch from deprecated `PanicInfo` to `PanicHookInfo`

Cargo.lock, Cargo.toml, src/interpreter/tests.rs, src/panic_hook.rs
After this is merged I'll be pushing a tag to trigger the release workflow and then assuming that works without issue (which it hasn't for the past few releases :upside_down_face:) I'll be publishing the new release on crates and GH
=> release: Update version to 0.5.0

Cargo.lock, Cargo.toml, src/interpreter/mod.rs, src/main.rs
This should fix #381 by percent decoding URLs before using them.
=> feat: percent decode urls

Cargo.lock, Cargo.toml, src/main.rs, src/opts/cli.rs, src/opts/config.rs, src/opts/mod.rs, src/opts/tests/parse.rs
This PR lets you pass the `-d` or `--decorations` boolean argument to enable/disable decorations, and enables winit's sctk-adwaita CSDs for Wayland compositors that don't use SSDs.
| prev (ugly) | this PR (CSD) | no decorations |
|-------------|---------------|----------------|
| ![image](https://github.com/user-attachments/assets/35bfc430-8409-47ff-99ab-8dac4a23fc93) | ![image](https://github.com/user-attachments/assets/aad42695-e6c0-4457-9a02-13254217f69d) | ![image](https://github.com/user-attachments/assets/7e048652-b721-4953-a313-800157449581) |
=> Make window decorations optional and use a better CSD on Wayland

src/image/mod.rs, src/interpreter/mod.rs, src/interpreter/snapshots/inlyne__interpreter__tests__image_loading_fails_gracefully.snap, src/interpreter/tests.rs, src/main.rs, src/renderer.rs, src/text.rs, src/utils.rs
This switches the behavior from panicking on poison errors to releasing the lock which shouldn't be a problem. If anything it's more correct
=> refactor: `std::sync::Mutex` -> `parking_lot::Mutex`

src/interpreter/html/element.rs, src/interpreter/mod.rs, src/interpreter/snapshots/inlyne__interpreter__tests__aligned_table.snap, src/interpreter/snapshots/inlyne__interpreter__tests__yaml_frontmatter.snap, src/renderer.rs, src/table.rs
Split out from #318 
Table headers were special-cased for some reason. We get the same result for a lot less code if we treat headers like bolded data cells instead
=> refactor: Treat table headers as bolded data cells

Cargo.lock, Cargo.toml, src/opts/mod.rs
dark-light detection failed for me (hyprland with xdg-desktop-portal-gtk and xdg-desktop-portal-hyprland) with version 1.1.1.
I updated it to 2.0.0 which works.
=> fix: update dark-light dependency to 2.0.0 and log any error
